apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: assignment3
  labels:
    app: order-service
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: "1.0.0"
    spec:
      restartPolicy: Always
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: APP_VERSION
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: SERVER_PORT
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: PRODUCT_SERVICE_URL
            - name: UNLEASH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: UNLEASH_API_URL
            - name: UNLEASH_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: UNLEASH_APP_NAME
            - name: UNLEASH_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: UNLEASH_ENVIRONMENT
            - name: UNLEASH_API_TOKEN
              value: "default:development.6be178343bae8003f1fd5df78529a0d35ae6adc82e3ae3b27f9529c2"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/orders
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/orders
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15
